### ISSUE TITLE
Custom Data

### ISSUE THREAD

**Issue by sidk99** [saic-vul/point_based_clothing#3]
Trying to run inference on custom data. However input seems to require additional segmentation data, that doesn't seem to be specified. What preprocessing steps are required?

**Comment by izakharkin** [comment]
Hello @sidk99,

Thank you for your interest in our work!

Sorry for the late reply, [here are the instructions](https://github.com/saic-vul/point_based_clothing#custom-data) that I added to README on how to get segmentations in the required format. After this procedure, the segmentation mask is loaded in [`load_segm()`](https://github.com/saic-vul/point_based_clothing/blob/a0fd1c53c7ed91000272b7f7a987c9ca1560da7d/src/dataloaders/loaders/cloth_base_loader.py#L75) and its result (which is simply a binary mask of lower+upper clothing) is used in a dataloader for model training or inference. 

Also, make sure that you have the SMPL-parameters of a person on your image or video frame.

Please let me know if something else is needed to run the pipeline on custom data.

**Comment by tabatabaeifateme** [comment]
Hello @izakharkin 
I have also tried to run inference on custom data, but I'm not able to get the SMPL-parameters. Could you please provide a repository or some instructions on how to obtain SMPL information?
