### ISSUE TITLE
Using rasterize from pytorch3d instead of nvdiffrast in get_smpl_rast ?

### ISSUE THREAD

**Issue by zhaofang0627** [saic-vul/point_based_clothing#5]
Hi, 

Thank you for sharing the great work! Is it possible to replace the rasterize function of nvdiffrast with pytorch3d's in [get_smpl_rast](https://github.com/saic-vul/point_based_clothing/blob/3650fdae2ba9a5ced40f3075a4f0fd995442a64e/src/models/pcd_renderer.py#L195)  because my server is CentOS which is not supported by nvdiffrast?

Thanks!

**Comment by izakharkin** [comment]
Hi, yes you can replace it with any differentiable rasterizer, e.g. with [pytorch3d](https://pytorch3d.readthedocs.io/en/v0.6.0/modules/renderer/rasterizer.html#pytorch3d.renderer.mesh.rasterize_meshes.rasterize_meshes)'s implementation.
