### ISSUE TITLE
geometric meta-model

### ISSUE THREAD

**Issue by caiyongqi** [saic-vul/point_based_clothing#7]
Hi, can the processed Cloth3D dataset used to train the geometric meta-model be made public?

**Comment by izakharkin** [comment]
Hi @caiyongqi , we are not planning to do that. Though it is not much different from the original [Cloth3D dataset](https://chalearnlap.cvc.uab.cat/dataset/38/description/), there were no special transformations for this dataset to make it suitable for traning
