### ISSUE TITLE
Link to download data 

### ISSUE THREAD

**Issue by agupta1812** [saic-vul/point_based_clothing#9]
Hi,

Can you please share the link for downloading the checkpoints as its requires access to download so can you do that for us ?

Download data
Download the SMPL neutral model from [SMPLify project page](https://smplify.is.tue.mpg.de/login.php):
Register, go to the Downloads section, download SMPLIFY_CODE_V2.ZIP, and unpack it;
Move smplify_public/code/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl to data/smpl_models/SMPL_NEUTRAL.pkl.
Download models checkpoints (~570 Mb): [Google Drive](https://drive.google.com/file/d/16QFuHhou_C4EY6GvKCgbJvgbkIycITHw/view?usp=sharing) and place them to the checkpoints/ folder;
Download a sample data we provide to check the appearance fitting (~480 Mb): [Google Drive](https://drive.google.com/file/d/13ma8J0-ah4sVn0uH_hYSoJ_GLMxFpoQa/view?usp=sharing), unpack it, and place psp/ folder to the samples/ folder.

**Comment by izakharkin** [comment]
Hello @agupta1812 , `checkpoints/` and `samples/` download links in [README.md](https://github.com/saic-vul/point_based_clothing/blob/main/README.md#download-data) were fixed.
